import Navbar from './Navbar'
import styles from '../../styles/Home.module.css'
import Head from 'next/head'
import Link from 'next/link'

const Dashboard = () => {
  return (
    <div>
      <Navbar />
      <Head>
        <title>Decentralized Cloud Storage System using Blockchain</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          <Link href='../../FileUpload'>
            <h2>
              File Upload <span>-&gt;</span>
            </h2>
          </Link>
          <a></a>
          <Link href='../components/allFiles'>
            <h2>
              Files Access <span>-&gt;</span>
            </h2>
          </Link>
          <a></a>
        </div>
      </main>
    </div>
  )
}

export default Dashboard
